version: '3'

services:

  mysql:
    image: mysql:8.0.2
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ifoody_db
      - LANG=en_US.utf8 # Study
    command: # Study
      - '--character-set-server=utf8'
      - '--collation-server=utf8_general_ci'
      - '--sql_mode='
    ports:
      - "3306:3306"
    volumes:
      - "./infra/db/scripts/tables.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./infra/db/scripts/triggers.sql:/docker-entrypoint-initdb.d/2.sql"
      - "./infra/db/scripts/data.sql:/docker-entrypoint-initdb.d/3.sql"
    networks:
      - ifoody-network

  # prometheus:
  #   image: prom/prometheus:v2.48.1
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
  #   networks:
  #     - ifoody-network

  # grafana:
  #   image: grafana/grafana-enterprise:10.2.2-ubuntu
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - ifoody-network

networks:
  ifoody-network:
    driver: bridge