version: '3'

services:
  mysql:
    image: mysql:8.0.2
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ifoody_db
    ports:
      - "3306:3306"
    volumes:
      - "./infra/db/scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"